apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-juridisk-vurdering-test-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykepenger-juridisk-vurdering.dev.intern.nav.no"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: api/health
  readiness:
    path: api/health
