apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flex-juridisk-vurdering-test-frontend
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 80Mi
  liveness:
    path: api/health
  readiness:
    path: api/health
  startup:
    path: api/health
    initialDelay: 10
  accessPolicy:
    outbound:
      external:
        - host: raw.githubusercontent.com
